name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependecies
      run: sudo apt-get update && sudo apt install libglfw3-dev libvulkan-dev libpulse-dev libpng-dev libjpeg-dev g++-9
    - name: build
      env:
        CXX: g++-9
      run: |
        mkdir build
        cd build
        cmake ..
        make
    - name: Install Dependecies
      run: cd ../deb-package && ./build.sh
