name: build

on: [push]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependecies
      run: sudo apt-get update && sudo apt install libglfw3-dev libvulkan-dev libpulse-dev libpng-dev libjpeg-dev g++-9
    - name: build
      env:
        CXX: g++-9
      run: |
        mkdir build && cd build
        cmake ..
        make
    - name: Build deb Package
      run: cd deb-package && ./build.sh

  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: prerequisites
      run: |
        brew install libsoundio libpng jpeg cmake make
        wget https://sdk.lunarg.com/sdk/download/1.2.131.2/mac/vulkansdk-macos-1.2.131.2.tar.gz
        tar -xf vulkansdk-macos-1.2.131.2.tar.gz
        wget https://github.com/glfw/glfw/releases/download/3.3.2/glfw-3.3.2.zip
        unzip -a glfw-3.3.2.zip
    - name: build
      env:
        CXX: clang++
      run: |
        mkdir build && cd build
        cmake .. -DVULKAN_SDK_PATH="vulkansdk-macos-1.2.131.2" -DGLFW_PATH="glfw-3.3.2" -DDISABLE_X11="a"
        make
    - name: app bundle
      run: cd MacOS && ./build.sh ../vulkansdk-macos-1.2.131.2
